//
//  Constants.h
//  TipCalculator
//
//  Created by Axel Rivera on 1/19/12.
//  Copyright (c) 2012 Axel Rivera. All rights reserved.
//

#define FLURRY_FULL_VERSION_KEY @"H8THHWFYTYHUT8PQTE3P"
#define FLURRY_FREE_VERSION_KEY @"9EZ8V7XPS989T8FUIBLK"

#define FLURRY_CALCULATE_TIP_EVENT @"CALCULATE_TIP"
#define FLURRY_CALCULATE_ADJUSTMENT_EVENT @"CALCULATE_ADJUSTMENT"
#define FLURRY_RESET_ADJUSTMENT_EVENT @"RESET_ADJUSTMENT"
#define FLURRY_DOWNLOAD_FULL_VERSION_EVENT @"DOWNLOAD_FULL_VERSION"
